version: "3.8"                                   # Compose file format; v3.8 is widely supported

services:
  nexus:                                         # Service name (your Nexus app)
    image: sonatype/nexus3:latest                # Pin a known-good version (avoid :latest drift)
    container_name: nexus                        # Stable name makes exec/logs easier
    restart: unless-stopped                      # Auto-restart on reboot/crash; not if you stopped it
    ports:
      - "8081:8081"                              # Expose UI/API on the host (http://HOST:8081)
      - "5000:5000"                              # (Optional) expose if you create a Docker Proxy repo on port 5000
      - "5001:5001"                              # (Optional) expose if you create a Docker Hosted repo on port 5001
    environment:
      TZ: "UTC"                                  # Consistent timestamps in logs
      INSTALL4J_ADD_VM_PARAMS: >-                # JVM settings for performance & stability
        -Xms2g -Xmx2g                            # Heap: adjust as your repos/metadata grow
        -XX:MaxDirectMemorySize=2g               # Off-heap buffers for I/O
        -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    volumes:
      - /srv/nexus-data:/nexus-data:rw           # Persist EVERYTHING (configs/db/blobs/logs) on host
    ulimits:
      nofile:
        soft: 65536                              # Lots of files/sockets under load
        hard: 65536
      nproc: 65535                               # Allow enough JVM threads
    security_opt:
      - no-new-privileges:true                   # Prevent privilege escalation inside the container
    cap_drop:
      - ALL                                      # Drop Linux capabilities (Nexus doesn’t need extra caps)
    stop_grace_period: 120s                      # Give JVM time to shut down cleanly
    healthcheck:                                 # Let Docker know when Nexus is actually ready
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/service/rest/v1/status | grep -q AVAILABLE"]
      interval: 30s
      timeout: 5s
      retries: 20
      start_period: 90s
    logging:                                     # Prevent log files from filling the disk
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
